### ISSUE TITLE
performance: PagingHelper RegexGroupBy.IsMatch

### ISSUE THREAD

**Issue by ArgoZhang** [CollaboratingPlatypus/PetaPoco#548] opened 2019-07-27 04:54 UTC
hi. using Page<T> query data in PP (MSSQLServer)

**GOOD**
```sql
select * from View_ETags where Category = 0 order by Id
```

**BAD**
```sql
select e.Id, s.GroupName, EID, StationName, e.PackageCount, WriteTime, WriteResult, Source, Elapsed, RSSI, e.Category from ETags e inner join stations s on e.stationname = s.name where Category = 0 order by e.Id
```

I found `RegexDistinct.IsMath` cost more than 10 seconds on my laptop. 
```c#
if (RegexDistinct.IsMatch(parts.SqlSelectRemoved) || RegexGroupBy.IsMatch(parts.SqlSelectRemoved))
{
    parts.SqlCount = sql.Substring(0, columnsGroup.Index) + "COUNT(*) FROM (" + parts.SqlCount + ") countAlias";
}
else
{
    parts.SqlCount = sql.Substring(0, columnsGroup.Index) + "COUNT(*) " + parts.SqlCount.Substring(columnsGroup.Index + columnsGroup.Length);
}
```
line 61 in PagingHelpers.cs file.
so Do we have to use Views for paging queries?
Can we improve the performance of this problem by refactoring?

**Comment by ArgoZhang** [comment] 2019-07-27 08:02
`RegexDistinct.IsMath` will slow down the performance if any column name appear before the From key word. Use * will work fine. like `select * from TableName`.
so i think need to find a new way to BuildPageQueriesSQL.

**Comment by ArgoZhang** [comment] 2019-07-27 09:08
UnitTest for this
```c#
public class DbTest : IDisposable
{
    private ITestOutputHelper _helper;
    private readonly IDatabase _db;

    public DbTest(ITestOutputHelper helper)
    {
        _helper = helper;
        _db = new Database<PetaPoco.Providers.SqlServerDatabaseProvider>("Data Source=.;Initial Catalog=BootstrapAdmin_PL;User ID=Pallet;Password=Argo@163.com");
    }

    [Fact]
    public void Page_Perf_Benchmarks()
    {
        Enumerable.Range(1, 20).ToList().ForEach(index =>
        {
            var goodElapsed = Page_Perf_Good();
            var badElapsed = Page_Perf_Bad();
            _helper.WriteLine($"{DateTimeOffset.Now} Good: {goodElapsed} Bad: {badElapsed}");
        });
    }

    public TimeSpan Page_Perf_Good()
    {
        var sql = new Sql("select * from Logs");
        return PageQuery(sql);
    }

    public TimeSpan Page_Perf_Bad()
    {
        var sql = new Sql("select Id, CRUD, UserName, LogTime, Ip, Browser, OS, City, RequestUrl, RequestData, UserAgent from Logs");
        return PageQuery(sql);
    }

    private TimeSpan PageQuery(Sql sql)
    {
        var sw = Stopwatch.StartNew();
        sql.OrderBy("LogTime desc");
        _db.Page<Log>(10, 20, sql);
        sw.Stop();
        return sw.Elapsed;
    }

    public void Dispose() => _db.Dispose();
}
```
**Result**
```log
27/07/2019 4:59:14 PM +08:00 Good: 00:00:00.4526851 Bad: 00:00:03.5946553
27/07/2019 4:59:18 PM +08:00 Good: 00:00:00.0954124 Bad: 00:00:04.0149426
27/07/2019 4:59:22 PM +08:00 Good: 00:00:00.0918765 Bad: 00:00:03.6234952
27/07/2019 4:59:26 PM +08:00 Good: 00:00:00.0803985 Bad: 00:00:03.6463631
27/07/2019 4:59:30 PM +08:00 Good: 00:00:00.0865740 Bad: 00:00:03.8221506
27/07/2019 4:59:33 PM +08:00 Good: 00:00:00.0809963 Bad: 00:00:03.6072916
27/07/2019 4:59:37 PM +08:00 Good: 00:00:00.0837606 Bad: 00:00:03.6710666
27/07/2019 4:59:41 PM +08:00 Good: 00:00:00.0816520 Bad: 00:00:03.6364303
27/07/2019 4:59:45 PM +08:00 Good: 00:00:00.1030800 Bad: 00:00:03.7362772
27/07/2019 4:59:48 PM +08:00 Good: 00:00:00.0836007 Bad: 00:00:03.6212818
27/07/2019 4:59:53 PM +08:00 Good: 00:00:00.2568562 Bad: 00:00:04.4603637
27/07/2019 4:59:58 PM +08:00 Good: 00:00:00.0855254 Bad: 00:00:04.7271171
27/07/2019 5:00:04 PM +08:00 Good: 00:00:00.1013155 Bad: 00:00:06.2888828
27/07/2019 5:00:09 PM +08:00 Good: 00:00:00.0904919 Bad: 00:00:04.7303123
27/07/2019 5:00:14 PM +08:00 Good: 00:00:00.0819561 Bad: 00:00:04.7338798
27/07/2019 5:00:19 PM +08:00 Good: 00:00:00.0897618 Bad: 00:00:04.7163292
27/07/2019 5:00:24 PM +08:00 Good: 00:00:00.0801766 Bad: 00:00:04.7128632
27/07/2019 5:00:28 PM +08:00 Good: 00:00:00.0818523 Bad: 00:00:04.6970128
27/07/2019 5:00:33 PM +08:00 Good: 00:00:00.0906429 Bad: 00:00:04.6346367
27/07/2019 5:00:38 PM +08:00 Good: 00:00:00.0987230 Bad: 00:00:04.5705266
```
Total 20 rows in Logs table.

**Comment by asherber** [comment] 2019-07-27 12:42
The problem is `RegexGroupBy`, which appears to be very sensitive to the length of the string passed in. It's not directly related to column names in the `SELECT` -- you can get the same effect by doing `SELECT *` and passing in a bunch of columns in the `ORDER BY`.

What's interesting is that `RegexOrderBy`, which is similarly complex, does not have performance issues.

@pleb  Can you give a description about what `RegexGroupBy` is looking for? Maybe there's a way to simplify it.

Anybody have a copy of RegexBuddy and can help with some debugging to see where the bottleneck might be?

**Comment by ArgoZhang** [comment] 2019-07-27 15:57
@asherber thank you very much. Is there any way to solve this performance problem?

**Comment by asherber** [comment] 2019-07-27 16:00
The regex can probably be improved. I'd like to get pleb's input on exactly what it's looking for.

**Comment by asherber** [comment] 2019-07-27 19:39
@butulia Can you help out here? `RegexGroupBy` turns out to be a major bottleneck when the sql is more than trivial. You can call `PagingHelper.Instance.SplitSQL()` with the two queries at the top of the page to see the difference.

**Comment by asherber** [comment] 2019-07-27 19:51
FWIW, [NPoco](https://github.com/schotime/NPoco/blob/master/src/NPoco/PagingHelper.cs) seems to always return the SQL that PetaPoco has at line 63 and never checks for `GROUP BY`. Is that a better approach to take? Or is there a reason that PetaPoco has the alternate SQL at line 67? If so, can `RegexGroupBy` be improved?

**Comment by ArgoZhang** [comment] 2019-07-28 03:07
@asherber I think throw an exception when miss Group by key work in sql is better than always check. PP can push this check on user side. what do you think?

**Comment by butulia** [comment] 2019-07-29 07:36
@asherber I've tried the regular expression with the above queries and you're right, it runs exceedingly slow. 
We made this regular expression to locate the `GROUP BY COL1, COL2, etc...` of the query completely based on the regular expression that already existed for the `ORDER BY` (`RegexOrderBy`), which attracts attention when seeing the time difference between the execution of one and the other.
I have tried with a quick modification of the regular expression (more by instinct than by understanding), and it seems to continue doing its work and much faster!
I put the modified `RegexGroupBy`, take a look and if you can a test and tell me!

```csharp
public Regex RegexGroupBy = new Regex(@"\bGROUP\s+BY\s+(?!.*?(?:\)|\s+)AS\s)(?:\((?>\((?<depth>)|\)(?<-depth>)|.?)*(?(depth)(?!))\)|[\[\]`""\w\(\)\.])+?(?:\s*,\s*(?:\((?>\((?<depth>)|\)(?<-depth>)|.?)*(?(depth)(?!))\)|[\[\]`""\w\(\)\.])+?)*",
                                              RegexOptions.RightToLeft | RegexOptions.IgnoreCase | RegexOptions.Multiline | RegexOptions.Singleline | RegexOptions.Compiled);
```

**Comment by butulia** [comment] 2019-07-29 11:50
@asherber 
We have reviewed the issue with the rest of the @promatcloud team.
We propose the pull request #549 with an optimization of the `RegexGroupBy` regular expression, and a new simpler `SimpleRegexGroupBy` regular expression to perform the check in this specific case.
We believe that with this `SimpleRegexGroupBy` it is sufficient for the verification that we originally wanted to perform, and we leave the `RegexGroupBy` optimized for possible future uses.

**Comment by ArgoZhang** [comment] 2019-07-29 17:17
nice work! according above unit test. the following is new result
```log
30/07/2019 1:14:35 AM +08:00 Good: 00:00:02.9105675 Bad: 00:00:00.2482028
30/07/2019 1:14:36 AM +08:00 Good: 00:00:00.5744124 Bad: 00:00:00.7775766
30/07/2019 1:14:38 AM +08:00 Good: 00:00:00.7600069 Bad: 00:00:00.6123719
30/07/2019 1:14:39 AM +08:00 Good: 00:00:00.6138613 Bad: 00:00:00.4324897
30/07/2019 1:14:40 AM +08:00 Good: 00:00:00.7968166 Bad: 00:00:00.2885117
30/07/2019 1:14:41 AM +08:00 Good: 00:00:00.3254481 Bad: 00:00:01.2296554
30/07/2019 1:14:42 AM +08:00 Good: 00:00:00.7760758 Bad: 00:00:00.4518584
30/07/2019 1:14:44 AM +08:00 Good: 00:00:00.9198026 Bad: 00:00:00.6145406
30/07/2019 1:14:45 AM +08:00 Good: 00:00:00.4301543 Bad: 00:00:00.7980470
30/07/2019 1:14:46 AM +08:00 Good: 00:00:00.6165277 Bad: 00:00:00.6129883
30/07/2019 1:14:48 AM +08:00 Good: 00:00:00.6136126 Bad: 00:00:00.9217738
30/07/2019 1:14:49 AM +08:00 Good: 00:00:00.9457314 Bad: 00:00:00.5905494
30/07/2019 1:14:50 AM +08:00 Good: 00:00:00.5343053 Bad: 00:00:00.4699674
30/07/2019 1:14:51 AM +08:00 Good: 00:00:00.3764728 Bad: 00:00:00.4735628
30/07/2019 1:14:53 AM +08:00 Good: 00:00:00.7713637 Bad: 00:00:00.4467564
30/07/2019 1:14:53 AM +08:00 Good: 00:00:00.6131090 Bad: 00:00:00.2425111
30/07/2019 1:14:55 AM +08:00 Good: 00:00:00.6809991 Bad: 00:00:01.1030727
30/07/2019 1:14:57 AM +08:00 Good: 00:00:01.3540793 Bad: 00:00:00.7719275
30/07/2019 1:14:58 AM +08:00 Good: 00:00:00.4553041 Bad: 00:00:00.6142241
30/07/2019 1:15:01 AM +08:00 Good: 00:00:01.5377400 Bad: 00:00:00.9199664
```
it looks very well.

**Comment by asherber** [comment] 2019-07-29 17:22
The original `RegexGroupBy`  is too dense for me to understand what it's looking for, which means that I can't evaluate the new one. And yes, `SimpleRegexGroupBy` is much faster, because it's just looking for a simple string, but I'm not familiar enough with complex SQL cases to know whether that's sufficient.

**Comment by pleb** [comment] 2019-08-01 22:29
Hi All. Sorry, I haven't replied earlier. 

Yes, the regexs for parsing queries has always been less than ideal. The correct way to do this would be to have a per-language parser that isn't based on regex. Obviously, though, that's a lot of work.

I'm happy for the PR to be merged. If we get regression, we can deal with it at that point. 

Good work everyone!

**Comment by pleb** [comment] 2019-08-02 03:34
Hey everyone, this is now in dev. Use the latest beta nuget package to try it out

**Comment by ArgoZhang** [comment] 2019-08-02 08:26
@pleb works very well. 👍

**Comment by pleb** [comment] 2019-10-30 00:49
We have a possible regression with the change. See #556 for more info

**Comment by ArgoZhang** [comment] 2019-11-06 02:56
@pleb The issue #556 cause by missing order by key word. so may i close this issue?

**Closed** 2019-12-03 03:06 UTC
