### ISSUE TITLE
enum Byte exception

### ISSUE THREAD

**Issue by fastlink30** [CollaboratingPlatypus/PetaPoco#197] opened 2015-05-07 09:16 UTC
i have problem with enumeration, if i try to get data from class like this:

....
        public DateTime? ALLADATA { get; set; } // datetime (0)
        public string CODIPIVA { get; set; } // nvarchar (11)
        public enuAlbergoXme HOTELXME { get; set; } // tinyint (0)
    }

and enuAlbergoXme is like this

```
public enum enuAlbergoXme : int
{
    NESSUNO = 0,
    A,
    B,
    C,
    D,
    E
}
```

is all ok, but if i declare enum as byte, i can't get data

Eccezione first-chance di tipo 'System.InvalidCastException' in Peta.dll
System.InvalidCastException: Cast specificato non valido.
   in petapoco_factory_0(IDataReader )
   in PetaPoco.Database.<Query>d__2`1.MoveNext() in c:\GIT\XME_C\Peta\Models\PetaPoco.cs:riga 884
SELECT \* FROM xm_rappo WHERE k_unique = @0
     -> @0 [Int32] = "442662"

is bug?

**Comment by Ste1io** [comment] 2023-09-27 20:26
Duplicate of #281

**Closed by Ste1io** 2023-09-27 20:26 UTC
Labels: investigate, bug
