### ISSUE TITLE
ExecuteReaderAsync does not close shared connection

### ISSUE THREAD

**Issue by shaunbowe** [CollaboratingPlatypus/PetaPoco#589] opened 2020-07-27 16:55 UTC
I recently upgraded to v6 from a much older version. Once we migrated I noticed we were running out of connections on the DB server. I tracked it down to this method not closing the shared connections. Just wondering if that is an oversight or it needs to remain open because of the IAsyncReader.

protected virtual async Task<IAsyncReader<T>> ExecuteReaderAsync<T>(CancellationToken cancellationToken, CommandType commandType, string sql,
                                                                            object[] args)
        {

**Comment by asherber** [comment] 2020-07-27 17:06
I believe this is by design. If you create a database with an `IDbConnection`, then you are responsible for all management of that connection -- you have to open it before it's used, and you have to close it when you're done. If you use any of the other `Database` constructors (connection string, connection string name, etc.), then the connection will be created, opened, and closed for you.

**Comment by shaunbowe** [comment] 2020-07-27 17:12
Thank you for your response, that is kind of what I figured. The only thing that seems strange to me, in this case, is that method calls OpenSharedConnection. If I am responsible for the connection I would assume that I am required to open it myself. Either way, not a big deal, it was just a strange behavior but I'm past it now. Thanks again.

**Comment by asherber** [comment] 2020-07-27 17:19
The naming is a little confusing. `OpenSharedConnection()` only opens the connection if PetaPoco created the connection (and if the connection is not already open). If you look at `SetupFromConnection()`, you'll see that `_sharedConnectionDepth` is set to `2`, which causes `OpenSharedConnection()` to think that the connection is already open and prevents it from doing anything.

**Closed** 2020-09-12 02:07 UTC
