### ISSUE TITLE
Nuget package install fails from console

### ISSUE THREAD

**Issue by jovball** [CollaboratingPlatypus/PetaPoco#236] opened 2016-01-17 23:23 UTC
It works from the GUI but not from the console. Anybody else having this issue?

PM> Install-Package PetaPoco
Install-Package : Unable to find package 'PetaPoco'.

**Comment by pleb** [comment] 2016-01-17 23:38
Hmmm. I'll flag this to be investigated

**Comment by pleb** [comment] 2016-01-22 00:22
Hi @jovball,

I've tried this in VS 2015 and couldn't reproduce.

    Install-Package PetaPoco 
    Attempting to gather dependencies information for package 'PetaPoco.5.1.121' with respect to project 'ConsoleApplication2', targeting '.NETFramework,Version=v4.5.2'
    Attempting to resolve dependencies for package 'PetaPoco.5.1.121' with DependencyBehavior 'Lowest'
    Resolving actions to install package 'PetaPoco.5.1.121'
    Resolved actions to install package 'PetaPoco.5.1.121'
    Adding package 'PetaPoco.5.1.121' to folder 'c:\users\plebm\documents\visual studio 2015\Projects\ConsoleApplication2\packages'
    Added package 'PetaPoco.5.1.121' to folder 'c:\users\plebm\documents\visual studio 2015\Projects\ConsoleApplication2\packages'
    Added package 'PetaPoco.5.1.121' to 'packages.config'
    Successfully installed 'PetaPoco 5.1.121' to ConsoleApplication2

Can you supply more details thanks?

**Comment by pleb** [comment] 2016-02-05 11:26
@jovball did you manage to reproduce this error? If you can't I might go ahead and close the issue

**Closed** 2016-02-09 00:01 UTC
Labels: bug, can not reproduce
