### ISSUE TITLE
PetaPoco.cs (Core) doesn't compile (Circular base class dependency)

### ISSUE THREAD

**Issue by MamadouSy** [CollaboratingPlatypus/PetaPoco#234] opened 2016-01-08 10:57 UTC
Hi,

First of all, I'd really like your API and have to says: Thanks you a lot!

I've just install the PetaPoco.Core version version 5.1.107-beta via nuget, I can't compile the code.
I've got the following error:

Circular base class dependency involving 'PetaPoco.DatabaseConfiguration' and 'PetaPoco.DatabaseConfiguration.IBuildConfigurationSettings'	PROJECT_PATH\Models\PetaPoco.cs	
Line 2455	, Column 18

I already know why and how to fix the error.
This happen because the class DatabaseConfiguration implements the interface IBuildConfigurationSettings which is define inside the DatabaseConfiguration:

```C#

    /// <summary>
    ///     A helper class which enables fluent configuration.
    /// </summary>
    public class DatabaseConfiguration : IDatabaseBuildConfiguration, DatabaseConfiguration.IBuildConfigurationSettings, IHideObjectMethods
    {
        private readonly IDictionary<string, object> _settings = new Dictionary<string, object>();

        public interface IBuildConfigurationSettings
```

If you move the interface outside the class (+ some little refactoring) everything is working fine!

Could you please take a look on that for the next version?

**Comment by pleb** [comment] 2016-01-08 11:55
Hi @MamadouSy, thanks for the report. I couldn't reproduce the error. I've upload the test project to https://github.com/pleb/PetaPocoBug1 and have made you a collaborator. Any chance you could try break it for me? Delete what's there and add your own solution/project if you like.

**Comment by MamadouSy** [comment] 2016-01-08 14:15
Hi Wade,

Thanks for you reply.

I have push the code on the repository you mention
https://github.com/pleb/PetaPocoBug1 <https://github.com/pleb/PetaPocoBug1>

I’ve added a readme which describe step by step what I’m doing.
There are also Screenshots (probably not useful)

I’m using Visual Studio 2013 Ultimate I don’t know if that make a difference or not.

I think that the problem is probably coming from the way I get the package.
Tell me if the steps I’m using are incorrect or if I can help more.

Thanks.

**Comment by pleb** [comment] 2016-01-10 08:37
OK, so I can replicate the issue when building via the command line and specifying tools version 4.0. If I set the VS project to use tools version 4.0, VS 2015 doesn't fail - sigh. I believe this is because Roslyn is is still compiling the code and doesn't honour the v4.0 build bug.

The next best thing to add it as a build step to the CI build script (https://github.com/CollaboratingPlatypus/PetaPoco/commit/1a7ae3fbfd87d8ecefbcd932e36c0154793bfeaf), which when run gives a [failed build](https://ci.appveyor.com/project/collaboratingplatypus/petapoco/build/5.1.108). And of course, after the [fix](https://github.com/CollaboratingPlatypus/PetaPoco/commit/ea1dc8668b4665f4f68282caf647612823b7feac) a [successful build](https://ci.appveyor.com/project/collaboratingplatypus/petapoco/build/5.1.109)

**Comment by pleb** [comment] 2016-01-10 08:38
@MamadouSy if you could confirm that it's fixed in 5.1.109-beta, I'll merge and release it

**Comment by MamadouSy** [comment] 2016-01-11 10:29
Hi Wade,

Yes that’s works for me. Many thanks.

**Comment by pleb** [comment] 2016-01-12 00:17
Awesome news mate!

**Closed by pleb** 2016-01-12 00:17 UTC
Labels: bug
