### ISSUE TITLE
public Task<int> UpdateAsync(object poco, IEnumerable<string> columns) does not work with POCO that has string primary key

### ISSUE THREAD

**Issue by groogiam** [CollaboratingPlatypus/PetaPoco#456] opened 2018-05-11 15:28 UTC
I reported this issue on the AsyncPoco project https://github.com/tmenier/AsyncPoco/issues/47
AsyncPoco was forked from this project so I suspect that PetaPoco may have the same issue.

**Comment by asherber** [comment] 2018-10-31 13:17
I ran your test project against current PetaPoco (from development branch), and everything worked fine for me.

Output of first `db.LastCommand`:

```
UPDATE [FeedStatus] SET [LastExecuted] = @0, [InProgressRequest] = @1 WHERE [FeedName] = @2
	 -> @0 [DateTime] = "10/31/2018 9:10:40 AM"
	 -> @1 [String] = "Test"
	 -> @2 [String] = "DeleteMe"
```

Output of second `db.LastCommand`:

```
UPDATE [FeedStatus] SET [InProgressRequest] = @0 WHERE [FeedName] = @1
	 -> @0 [String] = "Test"
	 -> @1 [String] = "DeleteMe"     
```

Closing this ticket, since the issue cannot be reproduced, but thank you for reporting.

**Closed by asherber** 2018-10-31 13:17 UTC
Labels: bug, investigate
